### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by ramn** [thiolliere/ruga#2]
cargo run --release
Segmentation fault: 11

Macbook Pro mid 2015, macOS Sierra, compiling from commit f40bded3a6649dccbc7816516cdc5d9f3530805e

**Comment by ramn** [comment]
Changing "#version 130" to "#version 150" in src/graphics/src/lib.rs solves the problem.

**Comment by thiolliere** [comment]
Thanks for the report and the correction,
But I don't know why it requires glsl 150 on your computer while it works with 130 on mine (which is on linux).
Is this a driver issue ?
However I'll update to 150 in master but if you have any explanation your welcome

**Comment by ramn** [comment]
I just googled a bit, seems to be macOS related

**Comment by thiolliere** [comment]
OK
