### ISSUE TITLE
I ran cargo build --release and some errors came up

### ISSUE THREAD

**Issue by shubhamkumar13** [thiolliere/ruga#4]
`error[E0277]: the trait bound `(): std::str::FromStr` is not satisfied
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/gilrs-0.3.1/src/mapping.rs:214:29
    |
214 |         let val = match val.parse() {
    |                             ^^^^^ the trait `std::str::FromStr` is not implemented for `()`

error[E0277]: the trait bound `(): std::slice::SliceIndex<u16>` is not satisfied
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/gilrs-0.3.1/src/mapping.rs:218:17
    |
218 |         buttons.get(val).cloned().ok_or(ParseSdlMappingError::InvalidBtn)
    |                 ^^^ the trait `std::slice::SliceIndex<u16>` is not implemented for `()`
    |
    = note: slice indices are of type `usize` or ranges of `usize`

error[E0277]: the trait bound `(): std::str::FromStr` is not satisfied
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/gilrs-0.3.1/src/mapping.rs:224:33
    |
224 |             let val = match val.parse() {
    |                                 ^^^^^ the trait `std::str::FromStr` is not implemented for `()`

error[E0277]: the trait bound `(): std::slice::SliceIndex<u16>` is not satisfied
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/gilrs-0.3.1/src/mapping.rs:228:18
    |
228 |             axes.get(val).cloned().ok_or(ParseSdlMappingError::InvalidAxis)
    |                  ^^^ the trait `std::slice::SliceIndex<u16>` is not implemented for `()`
    |
    = note: slice indices are of type `usize` or ranges of `usize`

error: aborting due to 4 previous errors

Build failed, waiting for other jobs to finish...
error: Could not compile `gilrs`.
`

I don't know exactly what happened, since I'm new to rust.

**Comment by vilunov** [comment]
Hey, I made a pull request fixing this, but meanwhile you can use my fork: https://github.com/vilunov/ruga

**Comment by thiolliere** [comment]
merged. thank you both.
